// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';


function Theme() {
  return /* module */[];
}

var scale = /* float array */[
  0,
  0.25,
  0.5,
  1,
  2,
  4
];

var Config = /* module */[/* scale */scale];

var Init = /* module */[];

exports.Theme = Theme;
exports.Config = Config;
exports.Init = Init;
/* No side effect */
