// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Styletron = require("@astrada/bs-styletron-react/lib/js/src/Styletron.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Css$BsCssCore = require("bs-css-core/lib/js/src/Css.js");

var component = ReasonReact.statelessComponent("Component");

function make(href, className, children) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("a", {
                  className: className,
                  href: href
                }, children);
    });
  return newrecord;
}

var Component = /* module */[
  /* component */component,
  /* make */make
];

function make$1(href, beep, children) {
  return Styletron.React[/* makeStyledComponent */2]((function () {
                return Css$BsCssCore.style(/* :: */[
                            Css$BsCssCore.flexGrow(1),
                            /* :: */[
                              Css$BsCssCore.flexBasis(Css$BsCssCore.rem(10)),
                              /* :: */[
                                Css$BsCssCore.backgroundColor(beep),
                                /* [] */0
                              ]
                            ]
                          ]);
              }), component, (function (param, param$1) {
                return make(href, param, param$1);
              }), children);
}

exports.Component = Component;
exports.make = make$1;
/* component Not a pure module */
