// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Styletron = require("@astrada/bs-styletron-react/lib/js/src/Styletron.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Css$BsCssCore = require("bs-css-core/lib/js/src/Css.js");

var theme = /* record */[/* textColor */Css$BsCssCore.purple];

function make(children) {
  return Styletron.React[/* makeStyled */1](/* `String */[
              -976970511,
              "nav"
            ], (function () {
                return Css$BsCssCore.style(/* :: */[
                            Css$BsCssCore.maxWidth(Css$BsCssCore.px(1000)),
                            /* :: */[
                              Css$BsCssCore.color(Css$BsCssCore.purple),
                              /* [] */0
                            ]
                          ]);
              }), { }, children);
}

var Nav = /* module */[/* make */make];

function make$1(children) {
  return Styletron.React[/* makeStyled */1](/* `String */[
              -976970511,
              "div"
            ], (function () {
                return Css$BsCssCore.style(/* :: */[
                            Css$BsCssCore.maxWidth(Css$BsCssCore.em(72.0)),
                            /* [] */0
                          ]);
              }), { }, children);
}

var Wrapper = /* module */[/* make */make$1];

function make$2(children) {
  return Styletron.React[/* makeStyled */1](/* `String */[
              -976970511,
              "h1"
            ], (function () {
                return Css$BsCssCore.style(/* :: */[
                            Css$BsCssCore.fontSize(Css$BsCssCore.rem(2.0)),
                            /* [] */0
                          ]);
              }), { }, children);
}

var Heading = /* module */[/* make */make$2];

function make$3(children) {
  return Styletron.React[/* makeStyled */1](/* `String */[
              -976970511,
              "h1"
            ], (function (props) {
                return Css$BsCssCore.style(/* :: */[
                            Css$BsCssCore.display(/* InlineBlock */11),
                            /* :: */[
                              Css$BsCssCore.backgroundColor(props.name),
                              /* :: */[
                                Css$BsCssCore.color(props.white),
                                /* [] */0
                              ]
                            ]
                          ]);
              }), { }, children);
}

var InlineColor = /* module */[/* make */make$3];

var component = ReasonReact.statelessComponent("Component");

function make$4(className, _, children) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: className
                }, children);
    });
  return newrecord;
}

var Component = /* module */[
  /* component */component,
  /* make */make$4
];

function make$5(s_, children) {
  return Styletron.React[/* makeStyledComponent */2]((function () {
                return Css$BsCssCore.style(s_);
              }), component, (function (param) {
                return (function (param$1) {
                    return make$4(param, s_, param$1);
                  });
              }), children);
}

var Flex = /* module */[
  /* Component */Component,
  /* make */make$5
];

exports.theme = theme;
exports.Nav = Nav;
exports.Wrapper = Wrapper;
exports.Heading = Heading;
exports.InlineColor = InlineColor;
exports.Flex = Flex;
/* component Not a pure module */
