// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Theme = require("./theme.bs.js");
var React = require("react");
var Styletron = require("@astrada/bs-styletron-react/lib/js/src/Styletron.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Css$BsCssCore = require("bs-css-core/lib/js/src/Css.js");

var component = ReasonReact.statelessComponent("Component");

function make(className, children) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", {
                          className: className
                        }, children);
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

var Component = /* module */[
  /* component */component,
  /* make */make
];

function makeStyled(styl, $staropt$star, children) {
  var el = $staropt$star ? $staropt$star[0] : "div";
  return Styletron.React[/* makeStyled */1](/* `String */[
              -976970511,
              el
            ], (function () {
                console.log(Css$BsCssCore.style(/* :: */[
                          Theme.px_(/* None */0, 2),
                          /* [] */0
                        ]));
                return Css$BsCssCore.style(styl);
              }), { }, children);
}

function make$1(children) {
  return makeStyled(/* :: */[
              Theme.pageWidth,
              /* :: */[
                Theme.px_(/* None */0, 4),
                /* [] */0
              ]
            ], /* None */0, children);
}

var Wrapper = /* module */[/* make */make$1];

function make$2(children) {
  return makeStyled(/* :: */[
              Css$BsCssCore.display(/* Flex */3),
              /* :: */[
                Css$BsCssCore.fontSize(Theme.Typography[/* four */3]),
                /* :: */[
                  Theme.m(0),
                  /* :: */[
                    Theme.p(4),
                    /* [] */0
                  ]
                ]
              ]
            ], /* Some */["ul"], children);
}

var NavItems = /* module */[/* make */make$2];

function make$3(children) {
  return makeStyled(/* :: */[
              Css$BsCssCore.listStyleType(/* None */14),
              /* :: */[
                Theme.px_(/* None */0, 1),
                /* [] */0
              ]
            ], /* Some */["li"], children);
}

var NavItem = /* module */[/* make */make$3];

function make$4(children) {
  return makeStyled(/* :: */[
              Css$BsCssCore.display(/* Flex */3),
              /* :: */[
                Css$BsCssCore.backgroundColor(Theme.Color[/* yellow */4]),
                /* :: */[
                  Theme.py(/* None */0, 5),
                  /* :: */[
                    Theme.mt(5),
                    /* [] */0
                  ]
                ]
              ]
            ], /* Some */["div"], children);
}

var Foot = /* module */[/* make */make$4];

function make$5(children) {
  return makeStyled(/* :: */[
              Css$BsCssCore.fontSize(Theme.Typography[/* one */0]),
              /* :: */[
                Css$BsCssCore.fontWeight(/* W700 */8),
                /* :: */[
                  Theme.m(0),
                  /* :: */[
                    Theme.py(/* None */0, 3),
                    /* [] */0
                  ]
                ]
              ]
            ], /* Some */["h1"], children);
}

var H1 = /* module */[/* make */make$5];

function make$6(children) {
  return makeStyled(/* :: */[
              Css$BsCssCore.fontSize(Theme.Typography[/* three */2]),
              /* :: */[
                Css$BsCssCore.fontWeight(/* W400 */5),
                /* :: */[
                  Theme.mt(5),
                  /* [] */0
                ]
              ]
            ], /* Some */["h2"], children);
}

var H2 = /* module */[/* make */make$6];

function make$7(children) {
  return makeStyled(/* :: */[
              Css$BsCssCore.fontSize(Theme.Typography[/* four */3]),
              /* :: */[
                Css$BsCssCore.fontWeight(/* W700 */8),
                /* :: */[
                  Theme.mt(3),
                  /* :: */[
                    Theme.mb(0),
                    /* [] */0
                  ]
                ]
              ]
            ], /* Some */["h3"], children);
}

var H3 = /* module */[/* make */make$7];

function make$8(children) {
  return makeStyled(/* :: */[
              Css$BsCssCore.fontSize(Theme.Typography[/* four */3]),
              /* :: */[
                Css$BsCssCore.fontWeight(/* W700 */8),
                /* :: */[
                  Css$BsCssCore.color(Css$BsCssCore.white),
                  /* :: */[
                    Theme.mt(3),
                    /* :: */[
                      Theme.mb(0),
                      /* [] */0
                    ]
                  ]
                ]
              ]
            ], /* Some */["h3"], children);
}

var H4 = /* module */[/* make */make$8];

function make$9(children) {
  return makeStyled(/* :: */[
              Css$BsCssCore.fontSize(Theme.Typography[/* four */3]),
              /* [] */0
            ], /* Some */["p"], children);
}

var P = /* module */[/* make */make$9];

function make$10(children) {
  return makeStyled(/* [] */0, /* Some */["span"], children);
}

var Span = /* module */[/* make */make$10];

function make$11(children) {
  return makeStyled(/* :: */[
              Css$BsCssCore.listStyleType(/* Square */2),
              /* :: */[
                Css$BsCssCore.fontSize(Theme.Typography[/* four */3]),
                /* :: */[
                  Theme.m(0),
                  /* :: */[
                    Theme.mt(2),
                    /* [] */0
                  ]
                ]
              ]
            ], /* Some */["ul"], children);
}

var Ul = /* module */[/* make */make$11];

function make$12(children) {
  return makeStyled(/* :: */[
              Css$BsCssCore.fontSize(Theme.Typography[/* four */3]),
              /* :: */[
                Theme.py(/* None */0, 2),
                /* [] */0
              ]
            ], /* Some */["li"], children);
}

var Li = /* module */[/* make */make$12];

function make$13(children) {
  return makeStyled(/* :: */[
              Css$BsCssCore.textDecoration(/* UnderlineWavy */Block.__(1, [Theme.Color[/* green */2]])),
              /* :: */[
                Css$BsCssCore.color(Css$BsCssCore.gray),
                /* [] */0
              ]
            ], /* Some */["span"], children);
}

var Wavy = /* module */[/* make */make$13];

function make$14($staropt$star, $staropt$star$1, children) {
  var color_ = $staropt$star ? $staropt$star[0] : Css$BsCssCore.white;
  var bg = $staropt$star$1 ? $staropt$star$1[0] : Theme.Color[/* purple */0];
  return makeStyled(/* :: */[
              Css$BsCssCore.display(/* InlineBlock */11),
              /* :: */[
                Css$BsCssCore.backgroundColor(Theme.Color[/* purple */0]),
                /* :: */[
                  Css$BsCssCore.color(color_),
                  /* :: */[
                    Css$BsCssCore.backgroundColor(bg),
                    /* :: */[
                      Theme.px_(/* None */0, 2),
                      /* [] */0
                    ]
                  ]
                ]
              ]
            ], /* None */0, children);
}

var Highlight = /* module */[/* make */make$14];

function make$15($staropt$star, children) {
  var color_ = $staropt$star ? $staropt$star[0] : Theme.Color[/* purple */0];
  return makeStyled(/* :: */[
              Css$BsCssCore.display(/* InlineBlock */11),
              /* :: */[
                Css$BsCssCore.borderBottomWidth(Theme.space(1)),
                /* :: */[
                  Css$BsCssCore.borderBottomColor(color_),
                  /* :: */[
                    Css$BsCssCore.borderBottomStyle(/* Solid */2),
                    /* [] */0
                  ]
                ]
              ]
            ], /* None */0, children);
}

var Underline = /* module */[/* make */make$15];

exports.Component = Component;
exports.makeStyled = makeStyled;
exports.Wrapper = Wrapper;
exports.NavItems = NavItems;
exports.NavItem = NavItem;
exports.Foot = Foot;
exports.H1 = H1;
exports.H2 = H2;
exports.H3 = H3;
exports.H4 = H4;
exports.P = P;
exports.Span = Span;
exports.Ul = Ul;
exports.Li = Li;
exports.Wavy = Wavy;
exports.Highlight = Highlight;
exports.Underline = Underline;
/* component Not a pure module */
