// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Theme = require("./theme.bs.js");
var React = require("react");
var Styletron = require("@astrada/bs-styletron-react/lib/js/src/Styletron.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Css$BsCssCore = require("bs-css-core/lib/js/src/Css.js");

var component = ReasonReact.statelessComponent("Component");

function make(_, className, children) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: className
                }, children);
    });
  return newrecord;
}

var Component = /* module */[
  /* component */component,
  /* make */make
];

function make$1(px, children) {
  return Styletron.React[/* makeStyledComponent */2]((function () {
                return Css$BsCssCore.style(/* :: */[
                            Theme.px_(/* None */0, px),
                            /* [] */0
                          ]);
              }), component, (function (param, param$1) {
                return make(px, param, param$1);
              }), children);
}

exports.Component = Component;
exports.make = make$1;
/* component Not a pure module */
