// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Css$BsCssCore = require("bs-css-core/lib/js/src/Css.js");

var scale = /* float array */[
  0,
  0.5,
  1,
  2,
  4
];

function s(x) {
  return Css$BsCssCore.em(Caml_array.caml_array_get(scale, x));
}

function p(x) {
  return Css$BsCssCore.padding(Css$BsCssCore.em(Caml_array.caml_array_get(scale, x)));
}

function py(x) {
  return Css$BsCssCore.padding2(Css$BsCssCore.em(Caml_array.caml_array_get(scale, x)), Css$BsCssCore.em(Caml_array.caml_array_get(scale, 0)));
}

function px(x) {
  return Css$BsCssCore.padding2(Css$BsCssCore.em(Caml_array.caml_array_get(scale, 0)), Css$BsCssCore.em(Caml_array.caml_array_get(scale, x)));
}

var m = Css$BsCssCore.margin;

var mr = Css$BsCssCore.marginRight;

var ml = Css$BsCssCore.marginLeft;

var mt = Css$BsCssCore.marginTop;

var mb = Css$BsCssCore.marginBottom;

exports.scale = scale;
exports.s = s;
exports.p = p;
exports.py = py;
exports.px = px;
exports.m = m;
exports.mr = mr;
exports.ml = ml;
exports.mt = mt;
exports.mb = mb;
/* Css-BsCssCore Not a pure module */
