// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("bs-platform/lib/js/caml_array.js");
var Css$BsCssCore = require("bs-css-core/lib/js/src/Css.js");

var pageWidth = Css$BsCssCore.maxWidth(Css$BsCssCore.em(52));

var scale = /* float array */[
  0,
  0.25,
  0.5,
  1,
  2,
  4
];

function space(x) {
  return Css$BsCssCore.rem(Caml_array.caml_array_get(scale, x));
}

function p(x) {
  return Css$BsCssCore.padding(Css$BsCssCore.rem(Caml_array.caml_array_get(scale, x)));
}

function py(x, y) {
  if (x) {
    return Css$BsCssCore.padding2(Css$BsCssCore.rem(Caml_array.caml_array_get(scale, x[0])), Css$BsCssCore.rem(Caml_array.caml_array_get(scale, y)));
  } else {
    return Css$BsCssCore.padding2(Css$BsCssCore.rem(Caml_array.caml_array_get(scale, y)), Css$BsCssCore.rem(Caml_array.caml_array_get(scale, 0)));
  }
}

function px_(y, x) {
  if (y) {
    return Css$BsCssCore.padding2(Css$BsCssCore.rem(Caml_array.caml_array_get(scale, x)), Css$BsCssCore.rem(Caml_array.caml_array_get(scale, y[0])));
  } else {
    return Css$BsCssCore.padding2(Css$BsCssCore.rem(Caml_array.caml_array_get(scale, 0)), Css$BsCssCore.rem(Caml_array.caml_array_get(scale, x)));
  }
}

function m(x) {
  return Css$BsCssCore.margin(Css$BsCssCore.rem(Caml_array.caml_array_get(scale, x)));
}

function mr(x) {
  return Css$BsCssCore.marginRight(Css$BsCssCore.rem(Caml_array.caml_array_get(scale, x)));
}

function ml(x) {
  return Css$BsCssCore.marginLeft(Css$BsCssCore.rem(Caml_array.caml_array_get(scale, x)));
}

function mt(x) {
  return Css$BsCssCore.marginTop(Css$BsCssCore.rem(Caml_array.caml_array_get(scale, x)));
}

function mb(x) {
  return Css$BsCssCore.marginBottom(Css$BsCssCore.rem(Caml_array.caml_array_get(scale, x)));
}

var purple = Css$BsCssCore.hex("996BDE");

var red = Css$BsCssCore.hex("FF4136");

var green = Css$BsCssCore.hex("2ECC40");

var gray = Css$BsCssCore.hex("AAAAAA");

var yellow = Css$BsCssCore.hex("ffc107");

var Color = /* module */[
  /* purple */purple,
  /* red */red,
  /* green */green,
  /* gray */gray,
  /* yellow */yellow
];

var one = Css$BsCssCore.px(72);

var two = Css$BsCssCore.px(48);

var three = Css$BsCssCore.px(36);

var four = Css$BsCssCore.px(24);

var five = Css$BsCssCore.px(18);

var six = Css$BsCssCore.px(12);

var Typography = /* module */[
  /* one */one,
  /* two */two,
  /* three */three,
  /* four */four,
  /* five */five,
  /* six */six
];

exports.pageWidth = pageWidth;
exports.scale = scale;
exports.space = space;
exports.p = p;
exports.py = py;
exports.px_ = px_;
exports.m = m;
exports.mr = mr;
exports.ml = ml;
exports.mt = mt;
exports.mb = mb;
exports.Color = Color;
exports.Typography = Typography;
/* pageWidth Not a pure module */
