// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Primatives = require("../utils/primatives.bs.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Css$BsCssCore = require("bs-css-core/lib/js/src/Css.js");

var component = ReasonReact.statelessComponent("Home");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.element(/* None */0, /* None */0, Primatives.Wrapper[/* make */0](/* array */[
                      ReasonReact.element(/* None */0, /* None */0, Primatives.H1[/* make */0](/* array */[ReasonReact.element(/* None */0, /* None */0, Primatives.Wavy[/* make */0](/* array */["Reasonable Website"]))])),
                      ReasonReact.element(/* None */0, /* None */0, Primatives.H2[/* make */0](/* array */[ReasonReact.element(/* None */0, /* None */0, Primatives.Highlight[/* make */0](/* None */0, /* None */0, /* array */["about"]))])),
                      ReasonReact.element(/* None */0, /* None */0, Primatives.P[/* make */0](/* array */[/* tuple */[
                                  "Reasonable website (RW) is a website boilerplate written in ",
                                  ReasonReact.element(/* None */0, /* None */0, Primatives.Wavy[/* make */0](/* array */["Reasonml."]))
                                ]])),
                      ReasonReact.element(/* None */0, /* None */0, Primatives.H2[/* make */0](/* array */[ReasonReact.element(/* None */0, /* None */0, Primatives.Highlight[/* make */0](/* None */0, /* None */0, /* array */["components"]))])),
                      ReasonReact.element(/* None */0, /* None */0, Primatives.P[/* make */0](/* array */["RW comes with a components, most of which you see now on the home page."])),
                      ReasonReact.element(/* None */0, /* None */0, Primatives.Ul[/* make */0](/* array */[/* tuple */[
                                  ReasonReact.element(/* None */0, /* None */0, Primatives.Li[/* make */0](/* array */[ReasonReact.element(/* None */0, /* None */0, Primatives.Highlight[/* make */0](/* None */0, /* Some */[Css$BsCssCore.gray], /* array */["H1, H2, P"]))])),
                                  ReasonReact.element(/* None */0, /* None */0, Primatives.Li[/* make */0](/* array */[ReasonReact.element(/* None */0, /* None */0, Primatives.Highlight[/* make */0](/* None */0, /* Some */[Css$BsCssCore.gray], /* array */["Wrapper"]))])),
                                  ReasonReact.element(/* None */0, /* None */0, Primatives.Li[/* make */0](/* array */[ReasonReact.element(/* None */0, /* None */0, Primatives.Highlight[/* make */0](/* None */0, /* Some */[Css$BsCssCore.gray], /* array */["etc.."]))]))
                                ]])),
                      ReasonReact.element(/* None */0, /* None */0, Primatives.H2[/* make */0](/* array */[ReasonReact.element(/* None */0, /* None */0, Primatives.Highlight[/* make */0](/* None */0, /* None */0, /* array */["styling"]))])),
                      ReasonReact.element(/* None */0, /* None */0, Primatives.P[/* make */0](/* array */["rw comes with a theme/styling thing. You get some style helpers:"])),
                      ReasonReact.element(/* None */0, /* None */0, Primatives.Ul[/* make */0](/* array */[/* tuple */[
                                  ReasonReact.element(/* None */0, /* None */0, Primatives.Li[/* make */0](/* array */[ReasonReact.element(/* None */0, /* None */0, Primatives.Highlight[/* make */0](/* None */0, /* Some */[Css$BsCssCore.gray], /* array */["p, px, py"]))])),
                                  ReasonReact.element(/* None */0, /* None */0, Primatives.Li[/* make */0](/* array */[ReasonReact.element(/* None */0, /* None */0, Primatives.Highlight[/* make */0](/* None */0, /* Some */[Css$BsCssCore.gray], /* array */["m, mt, mb, mr, ml"]))])),
                                  ReasonReact.element(/* None */0, /* None */0, Primatives.Li[/* make */0](/* array */[ReasonReact.element(/* None */0, /* None */0, Primatives.Highlight[/* make */0](/* None */0, /* Some */[Css$BsCssCore.gray], /* array */["etc..."]))]))
                                ]]))
                    ]));
    });
  return newrecord;
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
