// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Theme = require("../utils/theme.bs.js");
var Utils = require("../utils/utils.bs.js");
var React = require("react");
var Primatives = require("../utils/primatives.bs.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("About");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.element(/* None */0, /* None */0, Primatives.Wrapper[/* make */0](/* array */[
                      ReasonReact.element(/* None */0, /* None */0, Primatives.H1[/* make */0](/* array */[ReasonReact.element(/* None */0, /* None */0, Primatives.Wavy[/* make */0](/* array */["About"]))])),
                      ReasonReact.element(/* None */0, /* None */0, Primatives.P[/* make */0](/* array */["This page mostly exists to demonstrate routing capabilities. But just for kicks, below you'll find some future goals."])),
                      ReasonReact.element(/* None */0, /* None */0, Primatives.H2[/* make */0](/* array */[ReasonReact.element(/* None */0, /* None */0, Primatives.Highlight[/* make */0](/* None */0, /* None */0, /* array */["future goals"]))])),
                      ReasonReact.element(/* None */0, /* None */0, Primatives.Ul[/* make */0](/* array */[/* tuple */[
                                  ReasonReact.element(/* None */0, /* None */0, Primatives.Li[/* make */0](/* array */[ReasonReact.element(/* None */0, /* None */0, Primatives.Highlight[/* make */0](/* None */0, /* Some */[Theme.Color[/* gray */3]], /* array */["extract theme into a functor thing"]))])),
                                  ReasonReact.element(/* None */0, /* None */0, Primatives.Li[/* make */0](/* array */[ReasonReact.element(/* None */0, /* None */0, Primatives.Highlight[/* make */0](/* None */0, /* Some */[Theme.Color[/* gray */3]], /* array */["general purpose <Space /> util"]))])),
                                  ReasonReact.element(/* None */0, /* None */0, Primatives.Li[/* make */0](/* array */[React.createElement("a", {
                                                  href: "https://github.com/hew/reasonable-website/issues"
                                                }, Utils.str("more on github"))]))
                                ]]))
                    ]));
    });
  return newrecord;
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
