// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Utils = require("./utils.bs.js");
var React = require("react");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Future");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: "future"
                }, React.createElement("h1", undefined, Utils.str("Future Goals")), React.createElement("p", undefined, Utils.str("Future goals and bugs will be tracked on Github:")), React.createElement("p", undefined, React.createElement("a", {
                          href: "https://github.com/hew/reasonable-website/issues/"
                        }, Utils.str("Check them out"))));
    });
  return newrecord;
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
