// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Link = require("./link.bs.js");
var Utils = require("./utils.bs.js");
var React = require("react");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Home");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("div", {
                  className: "home"
                }, React.createElement("h1", undefined, Utils.str("Where We're At")), React.createElement("p", undefined, Utils.str("Hello there human. Welcome to Reasonable Website (RW).")), React.createElement("p", undefined, Utils.str("I created RW to start thinking about the web side of this whole Reasonml thing. Accordingly, RW demonstrates the following UI standards:")), React.createElement("ul", undefined, React.createElement("li", undefined, Utils.str("Fetching"), React.createElement("span", undefined, Utils.str(" (bs-fetch)"))), React.createElement("li", undefined, Utils.str("Decoding"), React.createElement("span", undefined, Utils.str(" (bs-json)"))), React.createElement("li", undefined, Utils.str("Routing "), React.createElement("span", undefined, Utils.str(" (reason-react)")))), React.createElement("p", undefined, Utils.str("To see everything in action, "), ReasonReact.element(/* None */0, /* None */0, Link.make("/repos", /* array */[Utils.str("check out my repos.")]))));
    });
  return newrecord;
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
