// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Styletron = require("@astrada/bs-styletron-react/lib/js/src/Styletron.js");
var Css$BsCssCore = require("bs-css-core/lib/js/src/Css.js");

function make(children) {
  return Styletron.React[/* makeStyled */1](/* `String */[
              -976970511,
              "div"
            ], (function () {
                return Css$BsCssCore.style(/* :: */[
                            Css$BsCssCore.maxWidth(Css$BsCssCore.px(150)),
                            /* :: */[
                              Css$BsCssCore.color(Css$BsCssCore.black),
                              /* [] */0
                            ]
                          ]);
              }), { }, children);
}

var Wrapper = /* module */[/* make */make];

exports.Wrapper = Wrapper;
/* Styletron Not a pure module */
