// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Utils = require("./utils.bs.js");
var React = require("react");
var Json_decode = require("bs-json/lib/js/src/Json_decode.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

function repo(json) {
  return /* record */[
          /* name */Json_decode.field("name", Json_decode.string, json),
          /* url */Json_decode.field("url", Json_decode.string, json),
          /* stars */Json_decode.field("stars", Json_decode.$$int, json),
          /* forks */Json_decode.field("forks", Json_decode.$$int, json)
        ];
}

function repos(json) {
  return Json_decode.array(repo, json);
}

var Decode = /* module */[
  /* repo */repo,
  /* repos */repos
];

var component = ReasonReact.reducerComponent("Counter");

function make() {
  var newrecord = component.slice();
  newrecord[/* didMount */4] = (function (self) {
      var handleReposLoaded = Curry._1(self[/* reduce */1], (function (repoData) {
              return /* Loaded */[repoData];
            }));
      fetch("https://hewtools.herokuapp.com").then((function (prim) {
                return prim.json();
              })).then((function (json) {
              var repos = Json_decode.array(repo, json);
              Curry._1(handleReposLoaded, repos);
              return Promise.resolve(/* () */0);
            }));
      return /* NoUpdate */0;
    });
  newrecord[/* render */9] = (function (param) {
      var repoList = $$Array.map((function (repo) {
              return React.createElement("p", undefined, Utils.str(repo[/* name */0]));
            }), param[/* state */2][/* data */0]);
      return React.createElement("div", {
                  className: "repos"
                }, React.createElement("h1", undefined, Utils.str("Hew's Github Repos")), React.createElement("p", undefined, Utils.str("The ol', data fetch, map a list. Are these linked or anything? Uh..")), React.createElement("hr", undefined), React.createElement("div", undefined, repoList));
    });
  newrecord[/* initialState */10] = (function () {
      return /* record */[/* data : array */[]];
    });
  newrecord[/* reducer */12] = (function (action, _) {
      return /* Update */Block.__(0, [/* record */[/* data */action[0]]]);
    });
  return newrecord;
}

exports.Decode = Decode;
exports.component = component;
exports.make = make;
/* component Not a pure module */
