// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Link = require("./utils/link.bs.js");
var Primatives = require("./utils/primatives.bs.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");
var Css$BsCssCore = require("bs-css-core/lib/js/src/Css.js");

var component = ReasonReact.statelessComponent("Beep");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.element(/* None */0, /* None */0, Primatives.Wrapper[/* make */0](/* array */[
                      ReasonReact.element(/* None */0, /* None */0, Primatives.Heading[/* make */0](/* array */["My name is Matthew Jones"])),
                      ReasonReact.element(/* None */0, /* None */0, Primatives.InlineColor[/* make */0](/* array */["yo"])),
                      ReasonReact.element(/* None */0, /* None */0, Primatives.Nav[/* make */0](/* array */["beep"])),
                      ReasonReact.element(/* None */0, /* None */0, Link.make("https://github.com/rtsao/styletron", Css$BsCssCore.bisque, /* array */["Link example"]))
                    ]));
    });
  return newrecord;
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
