// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Theme = require("./utils/theme.bs.js");
var Primatives = require("./utils/primatives.bs.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Beep");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.element(/* None */0, /* None */0, Primatives.Wrapper[/* make */0](/* array */[
                      ReasonReact.element(/* None */0, /* None */0, Primatives.Heading[/* make */0](/* array */["My name is Matthew Jones"])),
                      ReasonReact.element(/* None */0, /* None */0, Primatives.InlineColor[/* make */0](/* array */["yo"])),
                      ReasonReact.element(/* None */0, /* None */0, Primatives.Nav[/* make */0](/* array */["beep"])),
                      ReasonReact.element(/* None */0, /* None */0, Primatives.Flex[/* make */1](/* :: */[
                                Theme.p(2),
                                /* [] */0
                              ], /* array */[]))
                    ]));
    });
  return newrecord;
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
