// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Theme = require("./utils/theme.bs.js");
var Utils = require("./utils/utils.bs.js");
var Primatives = require("./utils/primatives.bs.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Beep");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return ReasonReact.element(/* None */0, /* None */0, Primatives.Wrapper[/* make */0](/* array */[
                      ReasonReact.element(/* None */0, /* None */0, Primatives.Heading[/* make */0](/* array */["My name is Matthew Jones"])),
                      ReasonReact.element(/* None */0, /* None */0, Primatives.Space[/* make */0](/* :: */[
                                Theme.p(2),
                                /* [] */0
                              ], /* array */[Utils.str("Hello")])),
                      ReasonReact.element(/* None */0, /* None */0, Primatives.Highlight[/* make */0](/* None */0, /* None */0, /* array */["Hello"])),
                      ReasonReact.element(/* None */0, /* None */0, Primatives.Underline[/* make */0](/* None */0, /* array */["Hello"]))
                    ]));
    });
  return newrecord;
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
