// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Nav = require("./components/nav.bs.js");
var Home = require("./pages/home.bs.js");
var More = require("./pages/more.bs.js");
var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Footer = require("./components/footer.bs.js");
var Styletron = require("@astrada/bs-styletron-react/lib/js/src/Styletron.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

function reducer(action, _) {
  return /* Update */Block.__(0, [/* record */[/* route */action[0]]]);
}

function mapUrlToRoute(url) {
  var match = url[/* path */0];
  if (match && match[0] === "more" && !match[1]) {
    return /* More */1;
  } else {
    return /* Home */0;
  }
}

var component = ReasonReact.reducerComponent("Router");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var match = self[/* state */2][/* route */0];
              return ReasonReact.element(/* None */0, /* None */0, Curry._2(Styletron.React[/* Provider */3][/* make */0], /* None */0, /* array */[React.createElement("div", undefined, ReasonReact.element(/* None */0, /* None */0, Nav.make(/* array */[])), React.createElement("main", undefined, match ? ReasonReact.element(/* None */0, /* None */0, More.make(/* array */[])) : ReasonReact.element(/* None */0, /* None */0, Home.make(/* array */[]))), ReasonReact.element(/* None */0, /* None */0, Footer.make(/* array */[])))]));
            }),
          /* initialState */(function () {
              return /* record */[/* route */mapUrlToRoute(ReasonReact.Router[/* dangerouslyGetInitialUrl */3](/* () */0))];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */reducer,
          /* subscriptions */(function (self) {
              return /* :: */[
                      /* Sub */[
                        (function () {
                            return ReasonReact.Router[/* watchUrl */1]((function (url) {
                                          return Curry._1(self[/* send */4], /* ChangeRoute */[mapUrlToRoute(url)]);
                                        }));
                          }),
                        ReasonReact.Router[/* unwatchUrl */2]
                      ],
                      /* [] */0
                    ];
            }),
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.reducer = reducer;
exports.mapUrlToRoute = mapUrlToRoute;
exports.component = component;
exports.make = make;
/* component Not a pure module */
