// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Utils = require("../utils/utils.bs.js");
var React = require("react");
var Primatives = require("../utils/primatives.bs.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("footer");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("footer", undefined, ReasonReact.element(/* None */0, /* None */0, Primatives.Foot[/* make */0](/* array */[ReasonReact.element(/* None */0, /* None */0, Primatives.Wrapper[/* make */0](/* array */[
                                    ReasonReact.element(/* None */0, /* None */0, Primatives.H4[/* make */0](/* array */["page meta"])),
                                    ReasonReact.element(/* None */0, /* None */0, Primatives.P[/* make */0](/* array */[/* tuple */[
                                                " view the source ",
                                                React.createElement("a", {
                                                      href: "https://github.com/hew/reasonable-website"
                                                    }, React.createElement("span", undefined, Utils.str("here."))),
                                                " made by ",
                                                React.createElement("a", {
                                                      href: "https://hew.tools"
                                                    }, React.createElement("span", undefined, Utils.str("hew.")))
                                              ]]))
                                  ]))])));
    });
  return newrecord;
}

var imgSrc = "https://user-images.githubusercontent.com/3103241/36555966-702746f4-17b8-11e8-83b3-777e63ed99da.png";

exports.component = component;
exports.imgSrc = imgSrc;
exports.make = make;
/* component Not a pure module */
