// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Route = require("./route.bs.js");
var Utils = require("../utils/utils.bs.js");
var React = require("react");
var Primatives = require("../utils/primatives.bs.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("nav");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      return React.createElement("nav", undefined, ReasonReact.element(/* None */0, /* None */0, Primatives.NavItems[/* make */0](/* array */[
                          ReasonReact.element(/* None */0, /* None */0, Primatives.NavItem[/* make */0](/* array */[ReasonReact.element(/* None */0, /* None */0, Route.make("/", /* array */[Utils.str("home")]))])),
                          ReasonReact.element(/* None */0, /* None */0, Primatives.NavItem[/* make */0](/* array */[ReasonReact.element(/* None */0, /* None */0, Route.make("/more", /* array */[Utils.str("more")]))]))
                        ])));
    });
  return newrecord;
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
