// Generated by BUCKLESCRIPT VERSION 3.0.0, PLEASE EDIT WITH CARE
'use strict';

var Route = require("./route.bs.js");
var Utils = require("../utils/utils.bs.js");
var React = require("react");
var Primatives = require("../utils/primatives.bs.js");
var ReasonReact = require("reason-react/lib/js/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("nav");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("nav", undefined, ReasonReact.element(/* None */0, /* None */0, Primatives.NavItems[/* make */0](/* array */[
                                  ReasonReact.element(/* None */0, /* None */0, Primatives.NavItem[/* make */0](/* array */[ReasonReact.element(/* None */0, /* None */0, Route.make("/", /* array */[Utils.str("home")]))])),
                                  ReasonReact.element(/* None */0, /* None */0, Primatives.NavItem[/* make */0](/* array */[ReasonReact.element(/* None */0, /* None */0, Route.make("/more", /* array */[Utils.str("more")]))]))
                                ])));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
